/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xyz_java_base_jni_TestHello */

#ifndef _Included_com_xyz_java_base_jni_TestHello
#define _Included_com_xyz_java_base_jni_TestHello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xyz_java_base_jni_TestHello
 * Method:    hello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xyz_java_base_jni_TestHello_hello
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
